import { Platform, StyleSheet } from 'react-native';

export const colors = {
  blue: '#1A365D',
  lightBlue: '#3B82F6',
  green: '#10B981',
  mint: '#E8FFF6',
  gray: '#F3F4F6',
  gray2: '#F8FAFC',
  border: '#E7EAEE',
  text: '#111827',
  muted: '#6B7280',
  white: '#FFFFFF',
  danger: '#DC2626',
  yellow: '#FACC15',
  page: '#FFFFFF',
};

export const fonts = {
  regular: 'Inter_400Regular',
  medium: 'Inter_500Medium',
  semibold: 'Inter_600SemiBold',
  bold: 'Inter_700Bold',
};

export const shadow = {
  shadowColor: '#0F172A',
  shadowOpacity: 0.045,
  shadowOffset: { width: 0, height: 5 },
  shadowRadius: 14,
  elevation: 2,
};

export const screenMaxWidth = 375;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.page,
  },
  content: {
    width: '100%',
    maxWidth: screenMaxWidth,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 100,
    position: 'relative',
  },
  stickyHeader: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderBottomColor: '#F1F5F9',
    borderBottomWidth: 1,
    paddingBottom: 16,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  h1: {
    color: colors.blue,
    fontFamily: fonts.bold,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 0,
  },
  h2: {
    color: colors.blue,
    fontFamily: fonts.bold,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0,
  },
  body: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 22,
  },
  muted: {
    color: colors.muted,
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.gray2,
    borderWidth: 1,
    borderColor: '#EEF2F7',
  },
  inputWrap: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#F8FAFC',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  input: {
    flex: 1,
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 14,
    paddingVertical: Platform.OS === 'web' ? 13 : 10,
    outlineStyle: 'none',
  },
  label: {
    color: colors.blue,
    fontFamily: fonts.semibold,
    fontWeight: '600',
    marginBottom: 8,
    marginTop: 16,
    fontSize: 13,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 11,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 18,
  },
  primaryText: {
    color: colors.white,
    fontFamily: fonts.semibold,
    fontWeight: '600',
    fontSize: 14,
  },
  greenButton: {
    minHeight: 50,
    borderRadius: 11,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 18,
  },
  outlineButton: {
    minHeight: 50,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 18,
  },
  linkText: {
    color: colors.lightBlue,
    fontFamily: fonts.semibold,
    fontWeight: '600',
    fontSize: 12,
  },
  chip: {
    borderRadius: 11,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: colors.gray2,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chipActive: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  chipText: {
    color: colors.text,
    fontFamily: fonts.medium,
    fontWeight: '500',
    fontSize: 12,
  },
  chipTextActive: {
    color: colors.white,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 15,
    marginBottom: 14,
    ...shadow,
  },
  softCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    padding: 16,
    marginBottom: 16,
    ...shadow,
  },
  squareIcon: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: colors.gray2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tag: {
    borderRadius: 6,
    backgroundColor: colors.gray,
    color: colors.text,
    fontFamily: fonts.medium,
    fontWeight: '500',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 6,
    overflow: 'hidden',
  },
  greenTag: {
    borderRadius: 6,
    backgroundColor: '#D1FAE5',
    color: colors.green,
    fontFamily: fonts.semibold,
    fontWeight: '600',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 6,
    overflow: 'hidden',
  },
  blueTag: {
    borderRadius: 6,
    backgroundColor: '#DBEAFE',
    color: colors.lightBlue,
    fontFamily: fonts.semibold,
    fontWeight: '600',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 6,
    overflow: 'hidden',
  },
  tagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
});
